# Generated by Django 5.2.5 on 2025-10-25 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="predictions/%Y/%m/%d/")),
                ("predicted_class", models.IntegerField()),
                ("confidence", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Prediction Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SimilarityHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_image", models.ImageField(upload_to="similarity/%Y/%m/%d/")),
                ("target_class", models.IntegerField()),
                ("similarity_score", models.FloatField()),
                ("distance", models.FloatField()),
                ("is_same_character", models.BooleanField()),
                (
                    "comparison_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="comparisons/%Y/%m/%d/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prediction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.predictionhistory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Similarity Histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
