# Generated by Django 5.2.5 on 2025-10-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="similarityhistory",
            name="comparison_image",
        ),
        migrations.AddField(
            model_name="similarityhistory",
            name="blended_overlay",
            field=models.ImageField(
                blank=True, null=True, upload_to="blended/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="similarityhistory",
            name="reference_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="references/%Y/%m/%d/"
            ),
        ),
    ]
