# Generated by Django 5.2.5 on 2025-11-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_similarityhistory_comparison_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="similarityhistory",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
    ]
